Create animals table
vvoo21/Vet-clinic pull request #1
Opened 2023-01-18 21:59 UTC by vvoo21

### Hi 🙋‍♀️,

In this pull request, I used a relational database to create the initial data structure for a vet clinic. 
- Used the [template](https://github.com/microverseinc/curriculum-template-databases) to generate the repository.
- Created a database named vet_clinic.
- Created a table named animals with the columns (id, name, date_of_birth, escape_attempts, neutered, weight_kg)
- Inserted the given data into the table
- Wrote queries for the given quests.
- Copied the SQL used to create the table into the schema.sql file in the generated repository.
- Copied the SQL used to insert data to the table into the data.sql file in the generated repository.
- Copied the SQL used to perform queries into the queries.sql file in the generated repository.

####  Screenshot of the results of my queries:

![query1](https://user-images.githubusercontent.com/108316220/213347695-25d2e873-c204-4e54-baf9-1a985b291bf3.png)
![query2](https://user-images.githubusercontent.com/108316220/213347697-3d1fa60a-5adb-4665-ba56-f59dd14e737e.png)
![query3](https://user-images.githubusercontent.com/108316220/213347699-eee23cbd-4611-41a4-950d-33c88dc18946.png)
![query4](https://user-images.githubusercontent.com/108316220/213347702-5c7ec571-ce28-422d-87e4-737853aa5331.png)
![query6](https://user-images.githubusercontent.com/108316220/213347703-c222b235-8e6f-47a6-a529-19144be4a80e.png)
![query7](https://user-images.githubusercontent.com/108316220/213347706-fbae07e0-4ea6-42ea-9cc4-c80233255d9a.png)
![query8](https://user-images.githubusercontent.com/108316220/213347707-8585e2b4-baa7-4836-9b49-590ccf7c44bb.png)

2023-01-18 22:23 UTC, Felix45 requested changes
Hi @vvoo21 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] Git flow is used correctly :heavy_check_mark: 
- [ ] Correct SQL statements :heavy_check_mark: 

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

## Required Changes ♻️
- [ ] Good job taking the screenshots, however, you forgot to include them in the description of this pull request. Kindly add the screenshots to the description of the pull request as specified in the project requirement.

![Screenshot from 2023-01-19 01-19-58](https://user-images.githubusercontent.com/16392046/213308095-3b2982e9-1063-4982-821a-f0351053fcf1.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 22:23 UTC, Felix45 commented on schema.sql
> +  id INT,
- [ Optional ] It would be better to make the `id` column `NOT NULL`  and a `PRIMARY KEY` these constraints make it easy to uniquely select a record using its primary key. You can make the column a primary key with the following `SQL` statement.
```SQL
  PRIMARY KEY (id)
```

2023-01-19 00:21 UTC, BenMukebo requested changes
Hi @vvoo21, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Gitflow is followed. :heavy_check_mark:


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly as requested by the previous reviewer, make sure you add screenshots of your queries results to the pull request description. This also helps to ensure that you run the queries with success. Kindly address this 👍🏻 Here is the project requiements 👇🏻 

![Screenshot from 2023-01-19 02-20-25](https://user-images.githubusercontent.com/79058364/213326419-94a5c364-cd96-47a3-8d13-826b02a6e65e.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly remember to customize the microverse `README` file template with your own information 👨🏻‍🎨 

![Screenshot from 2023-01-19 02-16-23](https://user-images.githubusercontent.com/79058364/213326059-d34ba912-cbed-4a48-8ee0-015eb0c930ff.png)


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 04:49 UTC, afanimartin approved these changes
Hi @vvoo21, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉 🎉 🎉 
- Requested changes made

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 14:31 UTC, merged